### ISSUE TITLE
02-Spark Post 작성

### ISSUE THREAD

**Issue by SoniaComp** [data-engineering-for-all-kr/data-engineering-for-all-kr.github.io#10]
## 공식문서
https://spark.apache.org/

## 개념 레퍼런스
* https://soniacomp.medium.com/apache-spark-%ED%95%98%EB%91%A1%EA%B3%BC-%EC%8A%A4%ED%8C%8C%ED%81%AC-%EC%B0%A8%EC%9D%B4%EC%A0%90-%EC%8A%A4%ED%8C%8C%ED%81%AC-%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EA%B3%BC-rdd-api-2-bcf1aaa4f186

## 실습 레퍼런스
* https://soniacomp.medium.com/getting-started-with-pyspark-rdd-spark-sql-a-10-minute-tutorial-8362fd4eed3b

## TODO
- [ ] 개념 (장단점, Hadoop 의 MapReduce 보다 좋은 점)
- [ ] 물리적 구조
- [ ] 논리적 구조(Spark API): RDD와 DataFrame 
- [ ] DAG
- [ ] 간단한 실습 소개 - 링크도 좋음
